### ISSUE TITLE
Connection challenges

### ISSUE THREAD

**Issue by jleecbd** [jbox-web/redmine_mail_checker#1]
I'm using a hosted email solution from Rackspace.  Yesterday I hit a certificate name mismatch, which caused an error, so I disabled SSL.  I now get the following error:  SSL_connect returned=1 errno=0 state=unknown state: unknown protocol.

**Comment by jleecbd** [comment]
POP reports that it works, although I'm not seeing a new issue populating in the project

**Comment by jleecbd** [comment]
Looking through the production log, it seems that the system is not permitting mail from unknown users .  I need that ability as most of my user community does not actively use Redmine.  I'm using it, in part, as a ticketing system.

**Comment by n-rodriguez** [comment]
> Looking through the production log, it seems that the system is not permitting mail from unknown users . I need that ability as most of my user community does not actively use Redmine. I'm using it, in part, as a ticketing system.

I think you may need this http://www.redminecrm.com/projects/helpdesk/pages/1.
It works with the Redmine CRM plugin which has a free version.
It creates Contact entities in Redmine for non-Redmine users so they can write you without having access to Redmine. You can define mail settings for each project, etc...

I'm not the creator of the Helpdesk plugin (one of their customers actually) but it works very well.

As mentioned in the README, this plugin is just a wrapper for the `bundle exec rake redmine:email:receive_imap` command and does nothing more than the rake command does.
There is no will of adding new features. Sorry.
