### ISSUE TITLE
Plugin doesn't recieve emails

### ISSUE THREAD

**Issue by puseidr** [jbox-web/redmine_mail_checker#2]
Hi, 
i'm trying to use this plugin with Redmine 2.1.6 (Ruby 1.9.3 Rails 3.2.11) but even with imap and/or pop3 i get the error "[ERROR] undefined method `extract_options_from_env' for MailHandler:Class"

**Comment by wzinet** [comment]
I have the same issue:
Environment:
  Redmine version                          2.2.3.stable
  Ruby version                             1.9.3 (x86_64-linux)
  Rails version                            3.2.12
  Environment                              production
  Database adapter                         Mysql2
Redmine plugins:
  redmine_mail_checker                     1.0.0

Logfile:
2015-09-09 20:49:29 +0000 [INFO] Checking IMAP mails
2015-09-09 20:49:29 +0000 [ERROR] undefined method `extract_options_from_env' for MailHandler:Class

Any suggestions?

**Comment by ghost** [comment]
> Any suggestions?

Update Redmine. This method doesn't exist for this Redmine version.

**Comment by wzinet** [comment]
I'll do that at some point.  In the meantime, could you update the description on the redmine plugins page - if it's not compatible with 2.2.x can you remove that version from the compatibility list.

Thanks

**Comment by ghost** [comment]
> I'll do that at some point. In the meantime, could you update the description on the redmine plugins page - if it's not compatible with 2.2.x can you remove that version from the compatibility list.

Sure!

**Comment by ghost** [comment]
Done!
