### ISSUE TITLE
Feature request: Checking Multiple Mailboxes

### ISSUE THREAD

**Issue by wzinet** [jbox-web/redmine_mail_checker#5]
I've got a bunch of users that I like to hide as much as possible from, so I've several email addresses that I check for email to add issues to different projects and different trackers.

Would it be possible to provide instructions to make multiple instances of this plugin, each checking a different mailbox, and each having different default destinations? (or is there a better way of doing this, without asking users to type a header)

**Comment by jobefp** [comment]
+1

**Comment by nnmalex** [comment]
+1
