### ISSUE TITLE
saving the plugin settings

### ISSUE THREAD

**Issue by pulsarinformatique** [jbox-web/redmine_mail_checker#6]
Hi

Whatever parameters I write in the /settings/plugin/redmine_mail_checker page when I save the page with the APPLY button I get a good messsage "sucess" but nothing is saved.

should we do something so that the settings are saved please ?

thanks

cyril

**Comment by Atmis** [comment]
I confirm the issue here. I have setup the plugin in October 2015 with Redmine 3.1, and at this time I was able to save the plugin settings. I am now using Redmine 3.4.1, and if I change one setting and save, all settings are cleared. I can still see the settings stored in the settings table in the DB but the plugin is not working anymore.

Thank you

Pierre

**Comment by Atmis** [comment]
Ok, I have been able to fix this problem. The settings were correctly saved, but the syntax changed for reading settings. I created a pull request #7. In the meantime, you can use the fork I created (https://github.com/Atmis/redmine_mail_checker)

**Comment by pulsarinformatique** [comment]
Hi

I downloaded the new files but it didn't change anything. I checked the 5 files you changed. They all have now the right syntax RedmineMailChecker.get_setting('xxx') though

should I say I'm on the following environment ?

  Redmine version                3.3.0.devel
  Ruby version                   2.3.0-p0 (2015-12-25) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2


Cyril

**Comment by Atmis** [comment]
My environment is a bit different :

Environment:
  Redmine version                3.4.2.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x64-mingw32]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2

Once again, I am not a developer, I just fixed the issue on my side by comparing the settings retrieval syntax in the plugin and Redmine documentation. There is not really more I can do.

**Comment by pulsarinformatique** [comment]
Ok, it's working now, I don't know why it didnt' work a few hours before (cache ?) but now users can reply to issues and forum threads directly via emails.

thanks a lot !

cyril
